## 📘 02_Cleaning.ipynb

1️⃣ Import des librairies

In [4]:
import pandas as pd
import numpy as np

2️⃣ Charger tous les datasets

In [5]:
df_population = pd.read_csv("../Shets/Table 1. Population size in eac.csv")
df_transport = pd.read_csv("../Shets/Table 2. Number of Tram and Bus.csv")
df_roads = pd.read_csv("../Shets/Table 3. Type of roads.csv")
df_land = pd.read_csv("../Shets/Table 4. Land use variables.csv")

3️⃣ Nettoyer les noms de colonnes

In [6]:
def clean_columns(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
        .str.replace("(", "")
        .str.replace(")", "")
    )
    return df

In [7]:
df_population = clean_columns(df_population)
df_transport = clean_columns(df_transport)
df_roads = clean_columns(df_roads)
df_land = clean_columns(df_land)

4️⃣ Vérifier les valeurs manquantes

In [8]:
df_population.isnull().sum()
df_transport.isnull().sum()
df_roads.isnull().sum()
df_land.isnull().sum()

commune                            0
zip_code                           0
region_area_m²                     0
parking_area_m²                    0
industrial_area__m²                0
parks_area__m²                     0
residential_area_m²                0
university/_institution_area_m²    0
number_of_commercial_buildings     0
dtype: int64

5️⃣ Vérifier les types de données

In [9]:
df_population.info()
print("\n")
df_transport.info()
print("\n")
df_roads.info()
print("\n")
df_land.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   commune          22 non-null     object
 1   zip_code         22 non-null     int64
 2   population_size  22 non-null     float64
 3   household        22 non-null     float64
 4   density          22 non-null     float64
dtypes: float64(3), int64(1), object(1)
memory usage: 1012.0+ bytes


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   commune       22 non-null     object
 1   zip_code      22 non-null     int64
 2   tram-station  22 non-null     int64
 3   bus-station   22 non-null     int64
dtypes: int64(3), object(1)
memory usage: 836.0+ bytes


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   commune                22 non-null     object
 1   zip_code               22 non-null     int64
 2   n°_of_primary_roads    22 non-null     int64
 3   n°_of_secondery_roads  22 non-null     int64
 4   n°_of_highways         22 non-null     int64
dtypes: int64(4), object(1)
memory usage: 1012.0+ bytes


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 9 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   commune                          22 non-null     object
 1   zip_code                         22 non-null     int64
 2   region_area_m²                   22 non-null     float64
 3   parking_area_m²                  22 non-null     float64
 4   industrial_area__m²              22 non-null     float64
 5   parks_area__m²                   22 non-null     float64
 6   residential_area_m²              22 non-null     float64
 7   university/_institution_area_m²  22 non-null     float64
 8   number_of_commercial_buildings   22 non-null     int64
dtypes: float64(6), int64(2), object(1)
memory usage: 1.7+ KB

6️⃣ Nettoyer les communes

In [10]:
def clean_commune(df):
    df["commune"] = df["commune"].str.strip().str.lower()
    return df

In [11]:
df_population = clean_commune(df_population)
df_transport = clean_commune(df_transport)
df_roads = clean_commune(df_roads)
df_land = clean_commune(df_land)

8️⃣ Sauvegarder les datasets propres

In [12]:
df_population.to_csv("../data_clean/population_clean.csv", index=False)
df_transport.to_csv("../data_clean/transport_clean.csv", index=False)
df_roads.to_csv("../data_clean/roads_clean.csv", index=False)
df_land.to_csv("../data_clean/landuse_clean.csv", index=False)

📘 02_Cleaning — Données trafic

1️⃣ Charger les fichiers Monday → Sunday

In [13]:
import pandas as pd

days = {
    "Monday": "Table 5. Monday.csv",
    "Tuesday": "Table 6. Tuesday.csv",
    "Wednesday": "Table 7. Wednesday.csv",
    "Thursday": "Table. 8 Thursday.csv",
    "Friday": "Table. 9 Friday.csv",
    "Saturday": "Table. 10 Saturday.csv",
    "Sunday": "Table. 11 Sunday.csv"
}

traffic_data = {}

for day, file in days.items():
    
    df = pd.read_csv(f"../Shets/{file}")
    
    # nettoyer colonnes
    df.columns = df.columns.str.strip().str.lower()
    
    # ajouter jour
    df["day"] = day
    
    traffic_data[day] = df

2️⃣ Fusionner tous les jours

In [14]:
df_traffic = pd.concat(traffic_data.values(), ignore_index=True)

df_traffic.head()

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

solution

In [31]:
days = {
    "Monday": "Table 5. Monday.csv",
    "Tuesday": "Table 6. Tuesday.csv",
    "Wednesday": "Table 7. Wednesday.csv",
    "Thursday": "Table. 8 Thursday.csv",
    "Friday": "Table. 9 Friday.csv",
    "Saturday": "Table. 10 Saturday.csv",
    "Sunday": "Table. 11 Sunday.csv"
}

traffic_data = {}

for day, file in days.items():

    df = pd.read_csv(f"../Shets/{file}")
    
    df = clean_columns(df)   # nettoyer les colonnes
    df["day"] = day          # ajouter le jour
    
    traffic_data[day] = df   # ⚡ IMPORTANT

certaines colonnes sont dupliquées dans tes fichiers CSV.

In [35]:
for day, file in days.items():

    df = pd.read_csv(f"../Shets/{file}")

    df = clean_columns(df)

    df = df.loc[:, ~df.columns.duplicated()]   # ⭐ corrige l'erreur

    df["day"] = day

    traffic_data[day] = df

In [36]:
## Ensuite concaténer
df_traffic = pd.concat(traffic_data.values(), ignore_index=True)

df_traffic.head()

,commune,zip_code,index,coordinates_debut,latitude_debut,longitude_debut,index.1,coordinates_fin,latitude_fin,longitude_fin,...,tti_min_at_15,tti_min_at_16,tti_min_at_17,tti_min_at_19,tti_min_at_20,tti_min_at_21,tti_min_at_22,tti_min_at_23,trt_min_at,tti_min_at
0,Echchallalate,28822,0,"33.56968640878232,-7.395306348809435",33.569686,-7.395306,1.0,"33.64792053315948,-7.408108582535458",33.647921,-7.408109,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Echchallalate,28822,0,"33.56968640878232,-7.395306348809435",33.569686,-7.395306,2.0,"33.615365940406214,-7.458959071198275",33.615366,-7.458959,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Echchallalate,28822,0,"33.56968640878232,-7.395306348809435",33.569686,-7.395306,3.0,"33.62789799357488,-7.44403942378749",33.627898,-7.444039,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Echchallalate,28822,0,"33.56968640878232,-7.395306348809435",33.569686,-7.395306,4.0,"33.601050398663844,-7.4844428526403695",33.601050,-7.484443,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Echchallalate,28822,1,"33.64792053315948,-7.408108582535458",33.647921,-7.408109,0.0,"33.56968640878232,-7.395306348809435",33.569686,-7.395306,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
## verification des colones dubliquee
df.columns[df.columns.duplicated()]

Index([], dtype='object')

## --------------------------------------------------

In [38]:
df_test = pd.read_csv("../Shets/Table 5. Monday.csv")
df_test.head()

,COMMUNE,ZIP code,index,Coordinates Debut,Latitude Debut,Longitude Debut,index.1,Coordinates Fin,Latitude Fin,Longitude Fin,...,TTI (min) at 14,TTI (min) at 15,TTI (min) at 16,TTI (min) at 17,TTI (min) at 18,TTI (min) at 19,TTI (min) at 20,TTI (min) at 21,TTI (min) at 22,TTI (min) at 23
0,Echchallalate,28822,0,"33.56968640878232,-7.395306348809435",33.569686,-7.395306,1,"33.64792053315948,-7.408108582535458",33.647921,-7.408109,...,1.024714,1.028062,1.024714,1.038109,1.034760,1.049829,1.026388,1.033086,1.029737,1.024714
1,Echchallalate,28822,0,"33.56968640878232,-7.395306348809435",33.569686,-7.395306,2,"33.615365940406214,-7.458959071198275",33.615366,-7.458959,...,1.395911,1.390415,1.401407,1.405071,1.388584,1.331795,1.317139,1.317139,1.322635,1.443541
2,Echchallalate,28822,0,"33.56968640878232,-7.395306348809435",33.569686,-7.395306,3,"33.62789799357488,-7.44403942378749",33.627898,-7.444039,...,1.213427,1.217207,1.230438,1.237998,1.236108,1.258789,1.241778,1.241778,1.237998,1.226658
3,Echchallalate,28822,0,"33.56968640878232,-7.395306348809435",33.569686,-7.395306,4,"33.601050398663844,-7.4844428526403695",33.601050,-7.484443,...,1.290248,1.290248,1.306088,1.313288,1.310408,1.320488,1.298888,1.298888,1.297448,1.297448
4,Echchallalate,28822,1,"33.64792053315948,-7.408108582535458",33.647921,-7.408109,0,"33.56968640878232,-7.395306348809435",33.569686,-7.395306,...,1.076619,1.093363,1.111781,1.103409,1.110106,1.098386,1.098386,1.098386,1.098386,1.091688

In [39]:
df_test = pd.read_csv("../Shets/Table 5. Monday.csv")
df_test.head()

,COMMUNE,ZIP code,index,Coordinates Debut,Latitude Debut,Longitude Debut,index.1,Coordinates Fin,Latitude Fin,Longitude Fin,...,TTI (min) at 14,TTI (min) at 15,TTI (min) at 16,TTI (min) at 17,TTI (min) at 18,TTI (min) at 19,TTI (min) at 20,TTI (min) at 21,TTI (min) at 22,TTI (min) at 23
0,Echchallalate,28822,0,"33.56968640878232,-7.395306348809435",33.569686,-7.395306,1,"33.64792053315948,-7.408108582535458",33.647921,-7.408109,...,1.024714,1.028062,1.024714,1.038109,1.034760,1.049829,1.026388,1.033086,1.029737,1.024714
1,Echchallalate,28822,0,"33.56968640878232,-7.395306348809435",33.569686,-7.395306,2,"33.615365940406214,-7.458959071198275",33.615366,-7.458959,...,1.395911,1.390415,1.401407,1.405071,1.388584,1.331795,1.317139,1.317139,1.322635,1.443541
2,Echchallalate,28822,0,"33.56968640878232,-7.395306348809435",33.569686,-7.395306,3,"33.62789799357488,-7.44403942378749",33.627898,-7.444039,...,1.213427,1.217207,1.230438,1.237998,1.236108,1.258789,1.241778,1.241778,1.237998,1.226658
3,Echchallalate,28822,0,"33.56968640878232,-7.395306348809435",33.569686,-7.395306,4,"33.601050398663844,-7.4844428526403695",33.601050,-7.484443,...,1.290248,1.290248,1.306088,1.313288,1.310408,1.320488,1.298888,1.298888,1.297448,1.297448
4,Echchallalate,28822,1,"33.64792053315948,-7.408108582535458",33.647921,-7.408109,0,"33.56968640878232,-7.395306348809435",33.569686,-7.395306,...,1.076619,1.093363,1.111781,1.103409,1.110106,1.098386,1.098386,1.098386,1.098386,1.091688